#!/usr/bin/env python3
# Copyright 2026 Yan Lu with DeepSeek V4 Flash and GPT-5.6-Luna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ============================================================================
# ext2fasthenry.py — ICsprout55 PEX JSON -> FastHenry2 .inp
# ============================================================================
# 3D quasi-static R(f)/L(f)/M(f) extraction for inductor/test structures:
# converts the same normalized routed-layout JSON used by rcx.py (see
# libs.tech/pex/rcx.py for the input contract) plus the gds2palace stackup
# (libs.tech/pex/palace/ics55_stackup.xml) into a FastHenry2 input deck.
#
# Conventions (verified against FastHenry2 examples):
#   .units uM (microns); segment sigma in 1/(um*ohm) = S/m / 1e6.
#   w = drawn segment width, h = metal thickness (stackup zmax-zmin),
#   z = layer mid-height, shifted so the substrate surface is z=0.
#   A g1 ground plane represents the lossy silicon substrate (sigma from the
#   stackup material, thick = substrate thickness).
#   Vias become short vertical segments (cut size by via name).
#   Ports become .external nodes.
#
# Usage:
#   python ext2fasthenry.py routed.json ics55_stackup.xml -o out.inp \
#       --fmin 1e8 --fmax 1e10 --ndec 20 [--nwinc 4 --nhinc 2]
# ============================================================================

import argparse
import json
import math
import re
import sys
import xml.etree.ElementTree as ET

# LEF via cut sizes (um) by via name; the PEX JSON vias carry these names.
VIA_CUT_UM = {"V1": 0.09, "V2": 0.09, "V3": 0.09, "V4": 0.09,
              "TV2": 0.36, "RV": 3.0}


class Stackup:
    """Metal/via layers (name -> zmin/zmax/material/gds layer) + materials."""

    def __init__(self, xml_path):
        root = ET.parse(xml_path).getroot()
        materials = {}
        for m in root.findall(".//Material"):
            name = m.get("Name")
            sigma = float(m.get("Conductivity", "0") or 0)
            materials[name] = sigma
        self.materials = materials
        self.layers = {}
        for lyr in root.findall(".//Layer"):
            name = lyr.get("Name")
            self.layers[name] = {
                "zmin": float(lyr.get("Zmin")),
                "zmax": float(lyr.get("Zmax")),
                "type": (lyr.get("Type") or "").upper(),
                "gds": int(lyr.get("Layer")),
                "sigma": materials.get(lyr.get("Material"), 0.0),
            }
        # substrate: the dielectric named Substrate (zmin..zmax, sigma)
        self.substrate = None
        for d in root.findall(".//Dielectric"):
            if d.get("Name") == "Substrate":
                self.substrate = {
                    "zmin": 0.0,
                    "zmax": float(d.get("Thickness")),
                    "sigma": materials.get(d.get("Material"), 0.0),
                }
        if self.substrate is None:
            sys.exit("ERROR: stackup has no dielectric named Substrate")

    def metal_z(self, layer_name):
        lyr = self.layers.get(layer_name)
        if lyr is None:
            sys.exit("ERROR: stackup has no layer named %s" % layer_name)
        # shift so the substrate surface is z=0
        return (lyr["zmin"] - self.substrate["zmax"],
                lyr["zmax"] - self.substrate["zmax"])


def convert(data, stackup, out_path, fmin, fmax, ndec, nwinc, nhinc):
    lines = ["* ICsprout55 FastHenry2 deck (generated by ext2fasthenry.py)",
             "* nets: %s" % ", ".join(n.get("name", "?") for n in data.get("nets", [])),
             ".units uM", ""]

    # substrate ground plane (lossy silicon), surface at z=0
    sz = stackup.substrate
    bbox = _layout_bbox(data, stackup)
    half = max(50.0, (bbox[2] - bbox[0]) / 2.0 + 20.0)
    lines.append("* lossy silicon substrate (sigma in 1/(um*ohm))")
    lines.append("g1 x1=%.4f y1=%.4f z1=0" % (-half, -half))
    lines.append("+  x2=%.4f y2=%.4f z2=0" % (half, -half))
    lines.append("+  x3=%.4f y3=%.4f z3=0" % (half, half))
    lines.append("+  thick=%.4f sigma=%.6g" % (sz["zmax"], sz["sigma"] / 1e6))
    lines.append("+  file=NONE")
    lines.append("")

    nodes = {}
    node_names = {}   # (net, layer, x, y) -> plain token (n1, n2, ...)
    seg_lines = []
    ext_ports = []

    def z_of(layer):
        zmin, zmax = stackup.metal_z(layer)
        return (zmin + zmax) / 2.0, zmax - zmin

    def node(key, x, y, z):
        if key not in node_names:
            node_names[key] = "n%d" % (len(node_names) + 1)
            nodes[key] = (x, y, z)
        return node_names[key]

    seg_no = 0
    for net in data.get("nets", []):
        net_name = net.get("name", "?")
        # segments (Manhattan, per the rcx.py contract)
        for seg in net.get("segments", []):
            layer = seg["layer"]
            zmid, h = z_of(layer)
            sigma = stackup.layers[layer]["sigma"] / 1e6
            if sigma <= 0:
                sys.exit("ERROR: layer %s has no conductivity in the stackup" % layer)
            x1, y1, x2, y2 = (float(seg["x1"]), float(seg["y1"]),
                              float(seg["x2"]), float(seg["y2"]))
            w = float(seg.get("width", 0))
            n1 = node((net_name, layer, x1, y1), x1, y1, zmid)
            n2 = node((net_name, layer, x2, y2), x2, y2, zmid)
            seg_no += 1
            seg_lines.append("e%d %s %s w=%.4f h=%.4f sigma=%.6g nwinc=%d nhinc=%d"
                             % (seg_no, n1, n2, w, h, sigma, nwinc, nhinc))
        # vias (vertical segments between the two metal layers)
        for via in net.get("vias", []):
            lower, upper = via["lower_layer"], via["upper_layer"]
            x, y = float(via["x"]), float(via["y"])
            zlo, _ = z_of(lower)
            zhi, _ = z_of(upper)
            zmid = (zlo + zhi) / 2.0
            h = abs(zhi - zlo)
            w = VIA_CUT_UM.get(via.get("name", ""), 0.09)
            sigma = stackup.layers.get(upper, {}).get("sigma", 0) / 1e6
            n1 = node((net_name, lower, x, y), x, y, zlo)
            n2 = node((net_name, upper, x, y), x, y, zhi)
            seg_no += 1
            seg_lines.append("e%d %s %s w=%.4f h=%.4f sigma=%.6g nwinc=%d nhinc=%d"
                             % (seg_no, n1, n2, w, h, sigma, nwinc, nhinc))
        # ports
        for port in net.get("ports", []):
            layer = port["layer"]
            zmid, _ = z_of(layer)
            key = node((net_name, layer, float(port["x"]), float(port["y"])),
                       float(port["x"]), float(port["y"]), zmid)
            ext_ports.append((port.get("name", key), key))

    for key, (x, y, z) in nodes.items():
        lines.append("%s x=%.4f y=%.4f z=%.4f" % (node_names[key], x, y, z))
    lines.append("")
    lines.extend(seg_lines)
    lines.append("")
    for port_name, key in ext_ports:
        lines.append(".external %s %s" % (key, port_name))
    lines.append("")
    lines.append(".freq fmin=%.6g fmax=%.6g ndec=%d" % (fmin, fmax, ndec))
    lines.append(".end")
    out_path.write("\n".join(lines) + "\n")
    print("wrote %s: %d nodes, %d segments, %d ports"
          % (out_path, len(nodes), seg_no, len(ext_ports)))


def _layout_bbox(data, stackup):
    xs, ys = [], []
    for net in data.get("nets", []):
        for seg in net.get("segments", []):
            xs += [float(seg["x1"]), float(seg["x2"])]
            ys += [float(seg["y1"]), float(seg["y2"])]
        for via in net.get("vias", []):
            xs.append(float(via["x"]))
            ys.append(float(via["y"]))
    if not xs:
        return (-100.0, -100.0, 100.0, 100.0)
    return (min(xs), min(ys), max(xs), max(ys))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("json", help="normalized routed-layout JSON (rcx.py input)")
    parser.add_argument("stackup", help="gds2palace stackup XML")
    parser.add_argument("-o", "--out", default="out.inp", help="output .inp file")
    parser.add_argument("--fmin", type=float, default=1e8)
    parser.add_argument("--fmax", type=float, default=1e10)
    parser.add_argument("--ndec", type=int, default=20)
    parser.add_argument("--nwinc", type=int, default=4)
    parser.add_argument("--nhinc", type=int, default=2)
    args = parser.parse_args(argv)

    data = json.load(open(args.json))
    stackup = Stackup(args.stackup)
    convert(data, stackup, open(args.out, "w"), args.fmin, args.fmax,
            args.ndec, args.nwinc, args.nhinc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
