# LAYERS_RC / VIAS_R (generated by libs.tech/pex/config_gen.py)
# BASE: released LEF seeds.  OVERRIDE: StarRC vendor ITF/CAPTAB.
# Keys: vendor corner names plus the flow/Liberty corner names the
# released libraries were characterized at (see the manifest).
set ::env(LAYERS_RC) [dict create \
  "typ" [dict create \
    MET1 [dict create R 0.11220 C 0.00076300] \
    MET2 [dict create R 0.09140 C 0.00110690] \
    MET3 [dict create R 0.09140 C 0.00110690] \
    MET4 [dict create R 0.09140 C 0.00110690] \
    MET5 [dict create R 0.09140 C 0.00062590] \
    T4M2 [dict create R 0.02390 C 0.00012990] \
    RDL [dict create R 0.01510 C 0.00005740] \
  ] \
  "rcbest" [dict create \
    MET1 [dict create R 0.08270 C 0.00077954] \
    MET2 [dict create R 0.06530 C 0.00112982] \
    MET3 [dict create R 0.06530 C 0.00113065] \
    MET4 [dict create R 0.06530 C 0.00113052] \
    MET5 [dict create R 0.06530 C 0.00064079] \
    T4M2 [dict create R 0.01688 C 0.00013310] \
    RDL [dict create R 0.01174 C 0.00006022] \
  ] \
  "rcworst" [dict create \
    MET1 [dict create R 0.14170 C 0.00074830] \
    MET2 [dict create R 0.11750 C 0.00108611] \
    MET3 [dict create R 0.11750 C 0.00108487] \
    MET4 [dict create R 0.11750 C 0.00108450] \
    MET5 [dict create R 0.11750 C 0.00061125] \
    T4M2 [dict create R 0.03092 C 0.00012688] \
    RDL [dict create R 0.01846 C 0.00005503] \
  ] \
  "cbest" [dict create \
    MET1 [dict create R 0.14170 C 0.00074303] \
    MET2 [dict create R 0.11750 C 0.00106312] \
    MET3 [dict create R 0.11750 C 0.00106414] \
    MET4 [dict create R 0.11750 C 0.00106666] \
    MET5 [dict create R 0.11750 C 0.00061011] \
    T4M2 [dict create R 0.03092 C 0.00012577] \
    RDL [dict create R 0.01846 C 0.00005920] \
  ] \
  "cworst" [dict create \
    MET1 [dict create R 0.08270 C 0.00078519] \
    MET2 [dict create R 0.06530 C 0.00116119] \
    MET3 [dict create R 0.06530 C 0.00115603] \
    MET4 [dict create R 0.06530 C 0.00115263] \
    MET5 [dict create R 0.06530 C 0.00064560] \
    T4M2 [dict create R 0.01688 C 0.00013445] \
    RDL [dict create R 0.01174 C 0.00005608] \
  ] \
  "nom_tt_025C_1v20" [dict create \
    MET1 [dict create R 0.11220 C 0.00076300] \
    MET2 [dict create R 0.09140 C 0.00110690] \
    MET3 [dict create R 0.09140 C 0.00110690] \
    MET4 [dict create R 0.09140 C 0.00110690] \
    MET5 [dict create R 0.09140 C 0.00062590] \
    T4M2 [dict create R 0.02390 C 0.00012990] \
    RDL [dict create R 0.01510 C 0.00005740] \
  ] \
  "nom_ss_125C_1v08" [dict create \
    MET1 [dict create R 0.14170 C 0.00078519] \
    MET2 [dict create R 0.11750 C 0.00116119] \
    MET3 [dict create R 0.11750 C 0.00115603] \
    MET4 [dict create R 0.11750 C 0.00115263] \
    MET5 [dict create R 0.11750 C 0.00064560] \
    T4M2 [dict create R 0.03092 C 0.00013445] \
    RDL [dict create R 0.01846 C 0.00005608] \
  ] \
  "nom_ff_n40C_1v32" [dict create \
    MET1 [dict create R 0.08270 C 0.00074303] \
    MET2 [dict create R 0.06530 C 0.00106312] \
    MET3 [dict create R 0.06530 C 0.00106414] \
    MET4 [dict create R 0.06530 C 0.00106666] \
    MET5 [dict create R 0.06530 C 0.00061011] \
    T4M2 [dict create R 0.01688 C 0.00012577] \
    RDL [dict create R 0.01174 C 0.00005920] \
  ] \
]
set ::env(VIAS_R) [dict create \
  "typ" [dict create \
    VIA1 [dict create res 2.000] \
    VIA2 [dict create res 2.000] \
    VIA3 [dict create res 2.000] \
    VIA4 [dict create res 2.000] \
    T4V2 [dict create res 0.250] \
  ] \
  "rcbest" [dict create \
    VIA1 [dict create res 1.800] \
    VIA2 [dict create res 1.800] \
    VIA3 [dict create res 1.800] \
    VIA4 [dict create res 1.800] \
    T4V2 [dict create res 0.225] \
  ] \
  "rcworst" [dict create \
    VIA1 [dict create res 2.200] \
    VIA2 [dict create res 2.200] \
    VIA3 [dict create res 2.200] \
    VIA4 [dict create res 2.200] \
    T4V2 [dict create res 0.275] \
  ] \
  "cbest" [dict create \
    VIA1 [dict create res 2.000] \
    VIA2 [dict create res 2.000] \
    VIA3 [dict create res 2.000] \
    VIA4 [dict create res 2.000] \
    T4V2 [dict create res 0.250] \
  ] \
  "cworst" [dict create \
    VIA1 [dict create res 2.000] \
    VIA2 [dict create res 2.000] \
    VIA3 [dict create res 2.000] \
    VIA4 [dict create res 2.000] \
    T4V2 [dict create res 0.250] \
  ] \
  "nom_tt_025C_1v20" [dict create \
    VIA1 [dict create res 2.000] \
    VIA2 [dict create res 2.000] \
    VIA3 [dict create res 2.000] \
    VIA4 [dict create res 2.000] \
    T4V2 [dict create res 0.250] \
  ] \
  "nom_ss_125C_1v08" [dict create \
    VIA1 [dict create res 2.200] \
    VIA2 [dict create res 2.200] \
    VIA3 [dict create res 2.200] \
    VIA4 [dict create res 2.200] \
    T4V2 [dict create res 0.275] \
  ] \
  "nom_ff_n40C_1v32" [dict create \
    VIA1 [dict create res 1.800] \
    VIA2 [dict create res 1.800] \
    VIA3 [dict create res 1.800] \
    VIA4 [dict create res 1.800] \
    T4V2 [dict create res 0.225] \
  ] \
]
