# LAYERS_RC / VIAS_R (generated by libs.tech/pex/config_gen.py; LEF values)
set ::env(LAYERS_RC) [dict create \
  "nom_*" [dict create \
    MET1 [dict create R 0.1122 C 0.0007630] \
    MET2 [dict create R 0.0914 C 0.0011069] \
    MET3 [dict create R 0.0914 C 0.0011069] \
    MET4 [dict create R 0.0914 C 0.0011069] \
    MET5 [dict create R 0.0914 C 0.0006259] \
    T4M2 [dict create R 0.0239 C 0.0001299] \
  ] \
]
set ::env(VIAS_R) [dict create \
  "nom_*" [dict create \
    VIA1 [dict create res 2.5] \
    VIA2 [dict create res 2.5] \
    VIA3 [dict create res 2.5] \
    VIA4 [dict create res 2.5] \
    T4V2 [dict create res 2.5] \
  ] \
]
