#!/usr/bin/env python3
"""ICS55 DRC fixture regression (KLayout self-consistency).

Generates minimal BEOL-only layouts -- one clean, plus one layout per
exercised rule (each with a single deliberate violation) -- runs the KLayout
DRC port on them, and asserts:

  - clean layout:    zero violations
  - perturbed layout: >=1 violation in the expected rule category

Fixtures are generated by klayout itself (tests/regression/make_fixtures.rb),
so geometry encoding is not reimplemented in Python.  Scope is narrow on
purpose: BEOL metal/via rules (exact tech-LEF values) are deterministic and
independent of the GDS-measured FEOL values.  This is KLayout
self-consistency evidence only; per the fail-closed policy
(tests/regression/README.md) it never claims Calibre parity.

klayout is located on PATH (--klayout), or via the LibreLane nix shell
(--librelane).  If neither provides klayout the check reports UNAVAILABLE
and exits 0 (tool absence is not a regression).

Usage:
  python3 drc_fixture_check.py [--librelane ~/Documents/librelane]
                               [--klayout PATH] [--out tests/regression/out]

Exit codes: 0 pass/unavailable, 1 fixture failures, 2 harness error.
"""
import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DRC_DECK = ROOT / "libs.tech" / "drc" / "ics55_drc.drc"
MAKE_FIXTURES = Path(__file__).resolve().parent / "make_fixtures.rb"

# Deck invocation switches: BEOL table only (see ics55_drc.drc usage).
DRC_SWITCHES = [
    "-rd", "tables=beol",
    "-rd", "no_feol=true", "-rd", "no_grid=true", "-rd", "no_advanced=true",
    "-rd", "no_density=true", "-rd", "no_mom=true", "-rd", "no_antenna=true",
]

# fixture name -> expected rule-category prefix (None for the clean fixture)
FIXTURES: dict[str, str | None] = {
    "clean": None,
    "m1_width": "metal.m1.width",
    "m1_space": "metal.m1.space",
    "m1_area": "metal.m1.area",
    "v1_width": "via.v1.width",
    "v1_enc": "via.v1.enc",
    "v1_space": "via.v1.space",
}


def find_klayout(args) -> tuple[str, str] | None:
    """Return (kind, executable) with kind 'bin' (direct) or 'nix' (nix shell)."""
    if args.klayout:
        return ("bin", args.klayout)
    if shutil.which("klayout"):
        return ("bin", "klayout")
    if args.librelane and Path(args.librelane).exists():
        return ("nix", str(args.librelane))
    return None


def run_klayout(kind: str, exe: str, script: Path, extra: list[str]) -> subprocess.CompletedProcess:
    base = ["-b", "-r", str(script)] + extra
    if kind == "nix":
        cmd = ["nix-shell", exe, "--run", " ".join(["klayout"] + base)]
    else:
        cmd = [exe] + base
    return subprocess.run(cmd, capture_output=True, text=True)


def run_drc(kind: str, exe: str, gds: Path, report: Path) -> subprocess.CompletedProcess:
    extra = ["-rd", f"input={gds}", "-rd", "top=TOP", "-rd", f"report={report}",
             "-rd", "tables=beol", "-rd", "no_feol=true", "-rd", "no_grid=true",
             "-rd", "no_advanced=true", "-rd", "no_density=true", "-rd", "no_mom=true",
             "-rd", "no_antenna=true"]
    base = ["-b", "-r", str(DRC_DECK)] + extra
    if kind == "nix":
        cmd = ["nix-shell", exe, "--run", " ".join(["klayout"] + base)]
    else:
        cmd = [exe] + base
    return subprocess.run(cmd, capture_output=True, text=True)


def read_violation_categories(report: Path) -> list[str]:
    """Item categories from a KLayout .lyrdb (XML)."""
    root = ET.parse(report).getroot()
    cats = []
    for item in root.findall(".//item"):
        cat = item.findtext("category", "")
        cats.append(cat.strip("'").strip())
    return sorted(set(c for c in cats if c))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--librelane", default=Path.home() / "Documents" / "librelane")
    ap.add_argument("--klayout", default=None)
    ap.add_argument("--out", default=ROOT / "tests" / "regression" / "out")
    args = ap.parse_args()

    klayout = find_klayout(args)
    out_dir = Path(args.out)
    fx_dir = out_dir / "fixtures"
    fx_dir.mkdir(parents=True, exist_ok=True)

    if not klayout:
        (out_dir / "drc_fixture_check.json").write_text(json.dumps({
            "schema": "ics55-drc-fixture-check/1.0",
            "status": "UNAVAILABLE",
            "reason": "klayout not found (PATH, --klayout, or --librelane nix shell)",
        }, indent=2))
        print("UNAVAILABLE (klayout not found)")
        return 0

    kind, exe = klayout

    # generate fixtures with klayout itself (no hand-rolled GDS writer)
    gen = run_klayout(kind, exe, MAKE_FIXTURES, ["-rd", f"out={fx_dir}"])
    if gen.returncode != 0:
        (out_dir / "drc_fixture_check.json").write_text(json.dumps({
            "schema": "ics55-drc-fixture-check/1.0",
            "status": "BLOCKED",
            "reason": f"fixture generation failed: {gen.stderr.strip().splitlines()[-3:]}",
        }, indent=2))
        print("BLOCKED (fixture generation failed)")
        return 2

    results = []
    rc = 0
    for name, expected in FIXTURES.items():
        gds = fx_dir / f"{name}.gds"
        report = fx_dir / f"{name}.lyrdb"
        r = run_drc(kind, exe, gds, report)
        rec: dict[str, Any] = {"fixture": name, "expected_category": expected}
        if r.returncode != 0 or not report.exists():
            rec["status"] = "BLOCKED"
            rec["reason"] = f"DRC run failed (rc={r.returncode}): " + (r.stderr.strip().splitlines() or ["no stderr"])[-3:]
            results.append(rec)
            rc = 2
            continue
        try:
            cats = read_violation_categories(report)
        except Exception as e:
            rec["status"] = "BLOCKED"
            rec["reason"] = f"lyrdb parse failed: {e}"
            results.append(rec)
            rc = 2
            continue
        rec["categories"] = cats
        if expected is None:
            rec["status"] = "PASS" if not cats else "FAIL"
            if cats:
                rec["issues"] = [f"clean layout flagged: {cats}"]
                rc = 1
        else:
            hit = [c for c in cats if c.startswith(expected)]
            rec["status"] = "PASS" if hit else "FAIL"
            if not hit:
                rec["issues"] = [f"expected category '{expected}*' not flagged; got {cats}"]
                rc = 1
        results.append(rec)

    (out_dir / "drc_fixture_check.json").write_text(json.dumps({
        "schema": "ics55-drc-fixture-check/1.0", "results": results,
        "deck_sha256": hashlib.sha256(DRC_DECK.read_bytes()).hexdigest(),
        "fixtures_sha256": hashlib.sha256(MAKE_FIXTURES.read_bytes()).hexdigest(),
    }, indent=2))
    for r in results:
        print(f"{r['status']:9s} {r['fixture']}" + (f"  - {r.get('issues')}" if r.get("issues") else ""))
    return rc


if __name__ == "__main__":
    sys.exit(main())
